#!/bin/bash

cd "${0%/*}" || exit 1

. ../functions.sh

exercises=(config/*.bashrc)

for exercise in "${exercises[@]}"; do
  while ! exercise::run "${exercise}"; do
    message::retry
  done
done

message::finished
